// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greetpb/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetManyTimeRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetManyTimeRequest) Reset()         { *m = GreetManyTimeRequest{} }
func (m *GreetManyTimeRequest) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimeRequest) ProtoMessage()    {}
func (*GreetManyTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{2}
}

func (m *GreetManyTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimeRequest.Unmarshal(m, b)
}
func (m *GreetManyTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimeRequest.Marshal(b, m, deterministic)
}
func (m *GreetManyTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimeRequest.Merge(m, src)
}
func (m *GreetManyTimeRequest) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimeRequest.Size(m)
}
func (m *GreetManyTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimeRequest proto.InternalMessageInfo

func (m *GreetManyTimeRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{3}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetManyTimeResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyTimeResponse) Reset()         { *m = GreetManyTimeResponse{} }
func (m *GreetManyTimeResponse) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimeResponse) ProtoMessage()    {}
func (*GreetManyTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{4}
}

func (m *GreetManyTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimeResponse.Unmarshal(m, b)
}
func (m *GreetManyTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimeResponse.Marshal(b, m, deterministic)
}
func (m *GreetManyTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimeResponse.Merge(m, src)
}
func (m *GreetManyTimeResponse) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimeResponse.Size(m)
}
func (m *GreetManyTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimeResponse proto.InternalMessageInfo

func (m *GreetManyTimeResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type LongGreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LongGreetRequest) Reset()         { *m = LongGreetRequest{} }
func (m *LongGreetRequest) String() string { return proto.CompactTextString(m) }
func (*LongGreetRequest) ProtoMessage()    {}
func (*LongGreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{5}
}

func (m *LongGreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetRequest.Unmarshal(m, b)
}
func (m *LongGreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetRequest.Marshal(b, m, deterministic)
}
func (m *LongGreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetRequest.Merge(m, src)
}
func (m *LongGreetRequest) XXX_Size() int {
	return xxx_messageInfo_LongGreetRequest.Size(m)
}
func (m *LongGreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetRequest proto.InternalMessageInfo

func (m *LongGreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type LongGreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetResponse) Reset()         { *m = LongGreetResponse{} }
func (m *LongGreetResponse) String() string { return proto.CompactTextString(m) }
func (*LongGreetResponse) ProtoMessage()    {}
func (*LongGreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{6}
}

func (m *LongGreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetResponse.Unmarshal(m, b)
}
func (m *LongGreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetResponse.Marshal(b, m, deterministic)
}
func (m *LongGreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetResponse.Merge(m, src)
}
func (m *LongGreetResponse) XXX_Size() int {
	return xxx_messageInfo_LongGreetResponse.Size(m)
}
func (m *LongGreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetResponse proto.InternalMessageInfo

func (m *LongGreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetEveryOneRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetEveryOneRequest) Reset()         { *m = GreetEveryOneRequest{} }
func (m *GreetEveryOneRequest) String() string { return proto.CompactTextString(m) }
func (*GreetEveryOneRequest) ProtoMessage()    {}
func (*GreetEveryOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{7}
}

func (m *GreetEveryOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryOneRequest.Unmarshal(m, b)
}
func (m *GreetEveryOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryOneRequest.Marshal(b, m, deterministic)
}
func (m *GreetEveryOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryOneRequest.Merge(m, src)
}
func (m *GreetEveryOneRequest) XXX_Size() int {
	return xxx_messageInfo_GreetEveryOneRequest.Size(m)
}
func (m *GreetEveryOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryOneRequest proto.InternalMessageInfo

func (m *GreetEveryOneRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetEveryOneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEveryOneResponse) Reset()         { *m = GreetEveryOneResponse{} }
func (m *GreetEveryOneResponse) String() string { return proto.CompactTextString(m) }
func (*GreetEveryOneResponse) ProtoMessage()    {}
func (*GreetEveryOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b39ee8dd19a4ff22, []int{8}
}

func (m *GreetEveryOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryOneResponse.Unmarshal(m, b)
}
func (m *GreetEveryOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryOneResponse.Marshal(b, m, deterministic)
}
func (m *GreetEveryOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryOneResponse.Merge(m, src)
}
func (m *GreetEveryOneResponse) XXX_Size() int {
	return xxx_messageInfo_GreetEveryOneResponse.Size(m)
}
func (m *GreetEveryOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryOneResponse proto.InternalMessageInfo

func (m *GreetEveryOneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetManyTimeRequest)(nil), "greet.GreetManyTimeRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.GreetResponse")
	proto.RegisterType((*GreetManyTimeResponse)(nil), "greet.GreetManyTimeResponse")
	proto.RegisterType((*LongGreetRequest)(nil), "greet.LongGreetRequest")
	proto.RegisterType((*LongGreetResponse)(nil), "greet.LongGreetResponse")
	proto.RegisterType((*GreetEveryOneRequest)(nil), "greet.GreetEveryOneRequest")
	proto.RegisterType((*GreetEveryOneResponse)(nil), "greet.GreetEveryOneResponse")
}

func init() { proto.RegisterFile("proto/greetpb/greet.proto", fileDescriptor_b39ee8dd19a4ff22) }

var fileDescriptor_b39ee8dd19a4ff22 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0xa1, 0x35, 0x19, 0x15, 0x75, 0xac, 0x5a, 0x53, 0x05, 0xc9, 0xc5, 0x42, 0xa1,
	0x2d, 0xd5, 0x9b, 0x07, 0xa1, 0xa2, 0x5e, 0xb4, 0x4a, 0xf4, 0xe4, 0x45, 0x52, 0x19, 0x43, 0xa0,
	0xd9, 0xc4, 0x4d, 0x5a, 0xe8, 0x2b, 0xf9, 0x94, 0x92, 0xcd, 0x6e, 0x4d, 0x56, 0xb1, 0x90, 0x53,
	0x3b, 0x7f, 0xf2, 0xfb, 0x66, 0xbe, 0x61, 0xe1, 0x28, 0xe6, 0x51, 0x1a, 0xf5, 0x7d, 0x4e, 0x94,
	0xc6, 0x93, 0xfc, 0xb7, 0x27, 0x72, 0x58, 0x17, 0x81, 0x73, 0x0b, 0xe6, 0x5d, 0xf6, 0x27, 0x60,
	0x3e, 0x9e, 0x00, 0x7c, 0x04, 0x3c, 0x49, 0xdf, 0x98, 0x17, 0x52, 0xcb, 0x38, 0x35, 0x3a, 0x96,
	0x6b, 0x89, 0xcc, 0xd8, 0x0b, 0x09, 0xdb, 0x60, 0x4d, 0x3d, 0x55, 0xad, 0x89, 0xaa, 0x99, 0x25,
	0xb2, 0xa2, 0x73, 0x09, 0x9b, 0x82, 0xe3, 0xd2, 0xe7, 0x8c, 0x92, 0x14, 0xbb, 0x60, 0xfa, 0x92,
	0x2b, 0x48, 0x1b, 0xc3, 0xed, 0x5e, 0x2e, 0xaf, 0xe4, 0xdc, 0x65, 0x83, 0x73, 0x0d, 0x4d, 0x91,
	0x7d, 0xf0, 0xd8, 0xe2, 0x25, 0x08, 0xa9, 0x12, 0xe4, 0x0c, 0xb6, 0xe4, 0x04, 0x49, 0x1c, 0xb1,
	0x84, 0xf0, 0x00, 0x1a, 0x9c, 0x92, 0xd9, 0x34, 0x95, 0xab, 0xc8, 0xc8, 0xe9, 0xc3, 0xbe, 0xa6,
	0xb6, 0xe2, 0x83, 0x2b, 0xd8, 0xb9, 0x8f, 0x98, 0x5f, 0x7d, 0xbf, 0x2e, 0xec, 0x16, 0x00, 0x2b,
	0xd4, 0x94, 0x19, 0x37, 0x73, 0xe2, 0x8b, 0x47, 0x56, 0xcd, 0x0c, 0xb5, 0xe3, 0x0f, 0xe4, 0x7f,
	0xd5, 0xe1, 0x57, 0x4d, 0x1e, 0xf0, 0x99, 0xf8, 0x3c, 0x78, 0x27, 0xbc, 0x80, 0xba, 0x88, 0x71,
	0xaf, 0xa8, 0x22, 0x87, 0xb1, 0x9b, 0xe5, 0x64, 0x0e, 0x77, 0xd6, 0x70, 0x2c, 0x8f, 0xa0, 0xbc,
	0xc5, 0x76, 0xb1, 0x51, 0xbb, 0xaf, 0x7d, 0xfc, 0x77, 0x51, 0xd1, 0x06, 0x06, 0x8e, 0xc0, 0x5a,
	0x3a, 0x87, 0x87, 0xb2, 0x5d, 0x3f, 0x86, 0xdd, 0xfa, 0x5d, 0x50, 0x8c, 0x8e, 0x81, 0x4f, 0x72,
	0x26, 0xe5, 0x45, 0x79, 0x26, 0xcd, 0xe6, 0xf2, 0x4c, 0xba, 0x7d, 0x19, 0x6f, 0x60, 0x8c, 0xac,
	0xd7, 0x75, 0xf9, 0xa4, 0x26, 0x0d, 0xf1, 0x9a, 0xce, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcd,
	0x3d, 0x97, 0xc7, 0x6a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	//Unary Request
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	//Stream Server
	GreetManyTime(ctx context.Context, in *GreetManyTimeRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimeClient, error)
	//Stream Client
	LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error)
	//Bi directional streaming
	GreetEveryOne(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryOneClient, error)
}

type greetServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetServiceClient(cc *grpc.ClientConn) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greet.GreetService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetManyTime(ctx context.Context, in *GreetManyTimeRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/greet.GreetService/GreetManyTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetManyTimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetManyTimeClient interface {
	Recv() (*GreetManyTimeResponse, error)
	grpc.ClientStream
}

type greetServiceGreetManyTimeClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetManyTimeClient) Recv() (*GreetManyTimeResponse, error) {
	m := new(GreetManyTimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[1], "/greet.GreetService/LongGreet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceLongGreetClient{stream}
	return x, nil
}

type GreetService_LongGreetClient interface {
	Send(*LongGreetRequest) error
	CloseAndRecv() (*LongGreetResponse, error)
	grpc.ClientStream
}

type greetServiceLongGreetClient struct {
	grpc.ClientStream
}

func (x *greetServiceLongGreetClient) Send(m *LongGreetRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceLongGreetClient) CloseAndRecv() (*LongGreetResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongGreetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) GreetEveryOne(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryOneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[2], "/greet.GreetService/GreetEveryOne", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetEveryOneClient{stream}
	return x, nil
}

type GreetService_GreetEveryOneClient interface {
	Send(*GreetEveryOneRequest) error
	Recv() (*GreetEveryOneResponse, error)
	grpc.ClientStream
}

type greetServiceGreetEveryOneClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetEveryOneClient) Send(m *GreetEveryOneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceGreetEveryOneClient) Recv() (*GreetEveryOneResponse, error) {
	m := new(GreetEveryOneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	//Unary Request
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	//Stream Server
	GreetManyTime(*GreetManyTimeRequest, GreetService_GreetManyTimeServer) error
	//Stream Client
	LongGreet(GreetService_LongGreetServer) error
	//Bi directional streaming
	GreetEveryOne(GreetService_GreetEveryOneServer) error
}

// UnimplementedGreetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (*UnimplementedGreetServiceServer) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedGreetServiceServer) GreetManyTime(req *GreetManyTimeRequest, srv GreetService_GreetManyTimeServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetManyTime not implemented")
}
func (*UnimplementedGreetServiceServer) LongGreet(srv GreetService_LongGreetServer) error {
	return status.Errorf(codes.Unimplemented, "method LongGreet not implemented")
}
func (*UnimplementedGreetServiceServer) GreetEveryOne(srv GreetService_GreetEveryOneServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetEveryOne not implemented")
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetManyTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyTimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).GreetManyTime(m, &greetServiceGreetManyTimeServer{stream})
}

type GreetService_GreetManyTimeServer interface {
	Send(*GreetManyTimeResponse) error
	grpc.ServerStream
}

type greetServiceGreetManyTimeServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetManyTimeServer) Send(m *GreetManyTimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_LongGreet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).LongGreet(&greetServiceLongGreetServer{stream})
}

type GreetService_LongGreetServer interface {
	SendAndClose(*LongGreetResponse) error
	Recv() (*LongGreetRequest, error)
	grpc.ServerStream
}

type greetServiceLongGreetServer struct {
	grpc.ServerStream
}

func (x *greetServiceLongGreetServer) SendAndClose(m *LongGreetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceLongGreetServer) Recv() (*LongGreetRequest, error) {
	m := new(LongGreetRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_GreetEveryOne_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).GreetEveryOne(&greetServiceGreetEveryOneServer{stream})
}

type GreetService_GreetEveryOneServer interface {
	Send(*GreetEveryOneResponse) error
	Recv() (*GreetEveryOneRequest, error)
	grpc.ServerStream
}

type greetServiceGreetEveryOneServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetEveryOneServer) Send(m *GreetEveryOneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceGreetEveryOneServer) Recv() (*GreetEveryOneRequest, error) {
	m := new(GreetEveryOneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetService_Greet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetManyTime",
			Handler:       _GreetService_GreetManyTime_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LongGreet",
			Handler:       _GreetService_LongGreet_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GreetEveryOne",
			Handler:       _GreetService_GreetEveryOne_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greetpb/greet.proto",
}
